# Generated by Django 4.1.2 on 2022-10-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekType', models.CharField(choices=[('Первая', 'Первая'), ('Вторая', 'Вторая')], max_length=20, verbose_name='Тип недели')),
                ('weekDay', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20, verbose_name='День недели')),
                ('groupNum', models.CharField(choices=[('x', 'Первая'), ('xx', 'Вторая')], max_length=20, verbose_name='Номер группы')),
                ('lessonNameFirst', models.CharField(blank=True, max_length=100, verbose_name='08:30-10:00')),
                ('additInfoFirst', models.CharField(blank=True, max_length=100, verbose_name='Дополнительная информация')),
                ('lessonNameSecond', models.CharField(blank=True, max_length=100, verbose_name='10:15-11:45')),
                ('additInfoSecond', models.CharField(blank=True, max_length=100, verbose_name='Дополнительная информация')),
                ('lessonNameThird', models.CharField(blank=True, max_length=100, verbose_name='12:30-14:00')),
                ('additInfoThird', models.CharField(blank=True, max_length=100, verbose_name='Дополнительная информация')),
                ('lessonNameFourth', models.CharField(blank=True, max_length=100, verbose_name='14:10-15:40')),
                ('additInfoFourth', models.CharField(blank=True, max_length=100, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
